// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6AM_jfdpzfoWQxhsEvJ079d9UyQ3QKOo',
    appId: '1:1060344635392:web:9ebb0e97c013a34713b8e5',
    messagingSenderId: '1060344635392',
    projectId: 'brewgo-f9855',
    authDomain: 'brewgo-f9855.firebaseapp.com',
    storageBucket: 'brewgo-f9855.firebasestorage.app',
    measurementId: 'G-76Z584LTMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFfeewcGzF1KHL8gZBIf6_0txJ6z3yR2w',
    appId: '1:1060344635392:android:d71efcad08104b8713b8e5',
    messagingSenderId: '1060344635392',
    projectId: 'brewgo-f9855',
    storageBucket: 'brewgo-f9855.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiPGy-hHvUyQpk616yk-dvcnCoG_Pmw9c',
    appId: '1:1060344635392:ios:0422af5de22ba7ca13b8e5',
    messagingSenderId: '1060344635392',
    projectId: 'brewgo-f9855',
    storageBucket: 'brewgo-f9855.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiPGy-hHvUyQpk616yk-dvcnCoG_Pmw9c',
    appId: '1:1060344635392:ios:0422af5de22ba7ca13b8e5',
    messagingSenderId: '1060344635392',
    projectId: 'brewgo-f9855',
    storageBucket: 'brewgo-f9855.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6AM_jfdpzfoWQxhsEvJ079d9UyQ3QKOo',
    appId: '1:1060344635392:web:e8da8d239eec16d213b8e5',
    messagingSenderId: '1060344635392',
    projectId: 'brewgo-f9855',
    authDomain: 'brewgo-f9855.firebaseapp.com',
    storageBucket: 'brewgo-f9855.firebasestorage.app',
    measurementId: 'G-9SDFW630JW',
  );
}
